using System.Diagnostics.CodeAnalysis;

// Most of the suppression below are for code that already shipped and cannot be changed.
//
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Point.Add(System.Drawing.Point,System.Drawing.Size):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Point.Ceiling(System.Drawing.PointF):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Point.Round(System.Drawing.PointF):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Point.Subtract(System.Drawing.Point,System.Drawing.Size):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Point.Truncate(System.Drawing.PointF):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.PointF.Add(System.Drawing.PointF,System.Drawing.Size):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.PointF.Add(System.Drawing.PointF,System.Drawing.SizeF):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.PointF.Subtract(System.Drawing.PointF,System.Drawing.Size):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.PointF.Subtract(System.Drawing.PointF,System.Drawing.SizeF):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1413:AvoidNonPublicFieldsInComVisibleValueTypes", Scope="type", Target="System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1413:AvoidNonPublicFieldsInComVisibleValueTypes", Scope="type", Target="System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point..ctor(System.Drawing.Size)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point..ctor(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point.Add(System.Drawing.Point,System.Drawing.Size):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point.Offset(System.Int32,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point.op_Addition(System.Drawing.Point,System.Drawing.Size):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point.op_Subtraction(System.Drawing.Point,System.Drawing.Size):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.Point.Subtract(System.Drawing.Point,System.Drawing.Size):System.Drawing.Point")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.Add(System.Drawing.PointF,System.Drawing.Size):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.Add(System.Drawing.PointF,System.Drawing.SizeF):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.op_Addition(System.Drawing.PointF,System.Drawing.Size):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.op_Addition(System.Drawing.PointF,System.Drawing.SizeF):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.op_Subtraction(System.Drawing.PointF,System.Drawing.Size):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.op_Subtraction(System.Drawing.PointF,System.Drawing.SizeF):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.Subtract(System.Drawing.PointF,System.Drawing.Size):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Drawing.PointF.Subtract(System.Drawing.PointF,System.Drawing.SizeF):System.Drawing.PointF")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1902:AvoidTestingForFloatingPointEquality", Scope="member", Target="System.Drawing.PointF.Equals(System.Object):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1902:AvoidTestingForFloatingPointEquality", Scope="member", Target="System.Drawing.PointF.op_Equality(System.Drawing.PointF,System.Drawing.PointF):System.Boolean")]

[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Size.Add(System.Drawing.Size,System.Drawing.Size):System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Size.Ceiling(System.Drawing.SizeF):System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Size.Round(System.Drawing.SizeF):System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Size.Subtract(System.Drawing.Size,System.Drawing.Size):System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.Size.Truncate(System.Drawing.SizeF):System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.SizeF.Add(System.Drawing.SizeF,System.Drawing.SizeF):System.Drawing.SizeF")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope="member", Target="System.Drawing.SizeF.Subtract(System.Drawing.SizeF,System.Drawing.SizeF):System.Drawing.SizeF")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1413:AvoidNonPublicFieldsInComVisibleValueTypes", Scope="type", Target="System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1413:AvoidNonPublicFieldsInComVisibleValueTypes", Scope="type", Target="System.Drawing.SizeF")]

// We explicitly suppress finalization on FontFamily, it is a singleton object.
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "System.Drawing.Font.Initialize(System.String,System.Single,System.Drawing.FontStyle,System.Drawing.GraphicsUnit,System.Byte,System.Boolean):System.Void")]

// If an exception is thrown here the app will likely die (must be an AV in GDI+).
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope="member", Target="System.Drawing.Graphics.BeginContainer(System.Drawing.Rectangle,System.Drawing.Rectangle,System.Drawing.GraphicsUnit):System.Drawing.Drawing2D.GraphicsContainer")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope="member", Target="System.Drawing.Graphics.BeginContainer(System.Drawing.RectangleF,System.Drawing.RectangleF,System.Drawing.GraphicsUnit):System.Drawing.Drawing2D.GraphicsContainer")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope="member", Target="System.Drawing.Graphics.BeginContainer():System.Drawing.Drawing2D.GraphicsContainer")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope="member", Target="System.Drawing.Graphics.Save():System.Drawing.Drawing2D.GraphicsState")]

[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="System.Drawing.Graphics.GetContextInfo():System.Object")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope="member", Target="System.Drawing.GraphicsContext.Dispose(System.Boolean):System.Void", MessageId="disposing")]

// Debug code.
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "System.Drawing.FontFamily..cctor()")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2002:DoNotLockOnObjectsWithWeakIdentity", Scope = "member", Target = "System.Drawing.FontFamily.SetNativeFamily(System.IntPtr):System.Void")]

//SafeHandles

[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.CodecName")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.SigPattern")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.SigMask")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.MimeType")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.FilenameExtension")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.DllName")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfoPrivate.FormatDescription")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.BitmapData.scan0")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.Imaging.PropertyItemInternal.value")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.SafeNativeMethods+PRINTDLGX86.lpfnPrintHook")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.SafeNativeMethods+PRINTDLGX86.lpfnSetupHook")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.SafeNativeMethods+PRINTDLG.lpfnPrintHook")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.SafeNativeMethods+PRINTDLG.lpfnSetupHook")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.NativeMethods.NullHandleRef")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.SafeNativeMethods.InvalidIntPtr")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Drawing.BufferedGraphics.targetDC")]

// LinkDemands
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Internal.DbgUtil.GetLastErrorStr():System.String")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Internal.WindowsGraphics.FromGraphics(System.Drawing.Graphics,System.Drawing.Internal.ApplyGraphicsProperties):System.Drawing.Internal.WindowsGraphics")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Internal.WindowsGraphics.Dispose(System.Boolean):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Internal.DeviceContext.Dispose(System.Boolean):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Internal.DeviceContext.get_Hdc():System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.EncoderParameters.ConvertFromMemory(System.IntPtr):System.Drawing.Imaging.EncoderParameters")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.EncoderParameters.ConvertToMemory():System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.Metafile.GetMetafileHeader():System.Drawing.Imaging.MetafileHeader")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.Metafile.GetMetafileHeader(System.IO.Stream):System.Drawing.Imaging.MetafileHeader")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.Metafile.GetMetafileHeader(System.String):System.Drawing.Imaging.MetafileHeader")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ImageAttributes.GetAdjustedPalette(System.Drawing.Imaging.ColorPalette,System.Drawing.Imaging.ColorAdjustType):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ImageAttributes.SetRemapTable(System.Drawing.Imaging.ColorMap[],System.Drawing.Imaging.ColorAdjustType):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfo.ConvertFromMemory(System.IntPtr,System.Int32):System.Drawing.Imaging.ImageCodecInfo[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfo.GetImageDecoders():System.Drawing.Imaging.ImageCodecInfo[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders():System.Drawing.Imaging.ImageCodecInfo[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.EncoderParameter.Dispose(System.Boolean):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.PropertyItemInternal.get_Value():System.Byte[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.PropertyItemInternal.Dispose(System.Boolean):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(System.IntPtr,System.Int32):System.Drawing.Imaging.PropertyItem[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.PropertyItemInternal.ConvertFromPropertyItem(System.Drawing.Imaging.PropertyItem):System.Drawing.Imaging.PropertyItemInternal")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ColorPalette.ConvertToMemory():System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Imaging.ColorPalette.ConvertFromMemory(System.IntPtr):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.EnumerateMetafile(System.Drawing.Imaging.Metafile,System.Drawing.PointF[],System.Drawing.Graphics+EnumerateMetafileProc,System.IntPtr,System.Drawing.Imaging.ImageAttributes):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.GetHalftonePalette():System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.Drawing.PointF[],System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawPolygon(System.Drawing.Pen,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawLines(System.Drawing.Pen,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawBeziers(System.Drawing.Pen,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.PointF[],System.Drawing.RectangleF,System.Drawing.GraphicsUnit,System.Drawing.Imaging.ImageAttributes,System.Drawing.Graphics+DrawImageAbort,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.Dispose(System.Boolean):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillRectangles(System.Drawing.Brush,System.Drawing.RectangleF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.Drawing.Point[],System.Single,System.Drawing.Drawing2D.FillMode):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.Point[],System.Drawing.Rectangle,System.Drawing.GraphicsUnit,System.Drawing.Imaging.ImageAttributes,System.Drawing.Graphics+DrawImageAbort,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawBeziers(System.Drawing.Pen,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawRectangles(System.Drawing.Pen,System.Drawing.RectangleF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.PointF[],System.Drawing.RectangleF,System.Drawing.GraphicsUnit):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.TransformPoints(System.Drawing.Drawing2D.CoordinateSpace,System.Drawing.Drawing2D.CoordinateSpace,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillPolygon(System.Drawing.Brush,System.Drawing.PointF[],System.Drawing.Drawing2D.FillMode):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawPolygon(System.Drawing.Pen,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillRectangles(System.Drawing.Brush,System.Drawing.Rectangle[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.EnumerateMetafile(System.Drawing.Imaging.Metafile,System.Drawing.PointF[],System.Drawing.RectangleF,System.Drawing.GraphicsUnit,System.Drawing.Graphics+EnumerateMetafileProc,System.IntPtr,System.Drawing.Imaging.ImageAttributes):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.EnumerateMetafile(System.Drawing.Imaging.Metafile,System.Drawing.Point[],System.Drawing.Graphics+EnumerateMetafileProc,System.IntPtr,System.Drawing.Imaging.ImageAttributes):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.Drawing.Point[],System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.Drawing.Point[],System.Drawing.Drawing2D.FillMode,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillPolygon(System.Drawing.Brush,System.Drawing.Point[],System.Drawing.Drawing2D.FillMode):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.Drawing.PointF[],System.Single,System.Drawing.Drawing2D.FillMode):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.Drawing.PointF[],System.Drawing.Drawing2D.FillMode,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.Drawing.Point[],System.Int32,System.Int32,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.TransformPoints(System.Drawing.Drawing2D.CoordinateSpace,System.Drawing.Drawing2D.CoordinateSpace,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.Drawing.PointF[],System.Int32,System.Int32,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawRectangles(System.Drawing.Pen,System.Drawing.Rectangle[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.DrawLines(System.Drawing.Pen,System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.EnumerateMetafile(System.Drawing.Imaging.Metafile,System.Drawing.Point[],System.Drawing.Rectangle,System.Drawing.GraphicsUnit,System.Drawing.Graphics+EnumerateMetafileProc,System.IntPtr,System.Drawing.Imaging.ImageAttributes):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.BufferedGraphicsContext.bFillBitmapInfo(System.IntPtr,System.IntPtr,System.Drawing.NativeMethods+BITMAPINFO_FLAT&):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.BufferedGraphicsContext.AllocBuffer(System.Drawing.Graphics,System.IntPtr,System.Drawing.Rectangle):System.Drawing.BufferedGraphics")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.BufferedGraphicsContext.CreateBuffer(System.IntPtr,System.Int32,System.Int32,System.Int32,System.Int32):System.Drawing.Graphics")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Pen.set_DashPattern(System.Single[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Pen.get_DashPattern():System.Single[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.ImageConverter.GetBitmapStream(System.Byte[]):System.IO.Stream")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SafeNativeMethods+Gdip.ConvertGPPOINTFArrayF(System.IntPtr,System.Int32):System.Drawing.PointF[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SafeNativeMethods+Gdip.ConvertGPPOINTArray(System.IntPtr,System.Int32):System.Drawing.Point[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SafeNativeMethods+Gdip.ConvertRectangleToMemory(System.Drawing.RectangleF[]):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SafeNativeMethods+Gdip.ConvertPointToMemory(System.Drawing.Point[]):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SafeNativeMethods+Gdip.ConvertPointToMemory(System.Drawing.PointF[]):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SafeNativeMethods+Gdip.ConvertRectangleToMemory(System.Drawing.Rectangle[]):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Icon.Initialize(System.Int32,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Icon.Save(System.IO.Stream):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Icon.ToBitmap():System.Drawing.Bitmap")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Icon.get_Size():System.Drawing.Size")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.NativeMethods+NONCLIENTMETRICS..ctor()")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.PrintPreviewGraphics.get_VisibleClipBounds():System.Drawing.RectangleF")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.FontFamily.get_Families():System.Drawing.FontFamily[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.UnsafeNativeMethods.PtrToStructure(System.IntPtr,System.Object):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.UnsafeNativeMethods.PtrToStructure(System.IntPtr,System.Type):System.Object")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.SystemFonts.get_IconTitleFont():System.Drawing.Font")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Region.GetRegionScans(System.Drawing.Drawing2D.Matrix):System.Drawing.RectangleF[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.get_PropertyItems():System.Drawing.Imaging.PropertyItem[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image._SetColorPalette(System.Drawing.Imaging.ColorPalette):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.Save(System.String,System.Drawing.Imaging.ImageCodecInfo,System.Drawing.Imaging.EncoderParameters):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.GetEncoderParameterList(System.Guid):System.Drawing.Imaging.EncoderParameters")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.GetPropertyItem(System.Int32):System.Drawing.Imaging.PropertyItem")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.SaveAdd(System.Drawing.Image,System.Drawing.Imaging.EncoderParameters):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.SaveAdd(System.Drawing.Imaging.EncoderParameters):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image._GetColorPalette():System.Drawing.Imaging.ColorPalette")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.Save(System.IO.Stream,System.Drawing.Imaging.ImageCodecInfo,System.Drawing.Imaging.EncoderParameters):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Image.get_FrameDimensionsList():System.Guid[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Font.GetHeight():System.Single")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Font.ToLogFont(System.Object):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Font.get_SizeInPoints():System.Single")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.BufferedGraphics.RenderInternal(System.Runtime.InteropServices.HandleRef,System.Drawing.BufferedGraphics):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.BufferedGraphics.Render(System.Drawing.Graphics):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.Get_PaperSources():System.Drawing.Printing.PaperSource[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.CreateMeasurementGraphics(System.Drawing.Printing.PageSettings):System.Drawing.Graphics")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.IsDirectPrintingSupported(System.Drawing.Image):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.Get_PrinterResolutions():System.Drawing.Printing.PrinterResolution[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.CreatePRINTDLG():System.Drawing.SafeNativeMethods+PRINTDLG")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.ReadOneDEVNAME(System.IntPtr,System.Int32):System.String")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.CreatePRINTDLGX86():System.Drawing.SafeNativeMethods+PRINTDLGX86")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal():System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.Get_PaperSizes():System.Drawing.Printing.PaperSize[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.PrinterSettings.IsDirectPrintingSupported(System.Drawing.Imaging.ImageFormat):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Printing.StandardPrintController.OnStartPage(System.Drawing.Printing.PrintDocument,System.Drawing.Printing.PrintPageEventArgs):System.Drawing.Graphics")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.PathGradientBrush._SetInterpolationColors(System.Drawing.Drawing2D.ColorBlend):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.PathGradientBrush._GetBlend():System.Drawing.Drawing2D.Blend")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.PathGradientBrush._GetInterpolationColors():System.Drawing.Drawing2D.ColorBlend")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.PathGradientBrush._SetBlend(System.Drawing.Drawing2D.Blend):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.LinearGradientBrush._SetInterpolationColors(System.Drawing.Drawing2D.ColorBlend):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.LinearGradientBrush._GetBlend():System.Drawing.Drawing2D.Blend")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.LinearGradientBrush._GetInterpolationColors():System.Drawing.Drawing2D.ColorBlend")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.LinearGradientBrush._SetBlend(System.Drawing.Drawing2D.Blend):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPathIterator.CopyData(System.Drawing.PointF[]&,System.Byte[]&,System.Int32,System.Int32):System.Int32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPathIterator.Enumerate(System.Drawing.PointF[]&,System.Byte[]&):System.Int32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddBeziers(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddClosedCurve(System.Drawing.PointF[],System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddLines(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddRectangles(System.Drawing.Rectangle[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddBeziers(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.Warp(System.Drawing.PointF[],System.Drawing.RectangleF,System.Drawing.Drawing2D.Matrix,System.Drawing.Drawing2D.WarpMode,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddLines(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddRectangles(System.Drawing.RectangleF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddClosedCurve(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddCurve(System.Drawing.Point[],System.Int32,System.Int32,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddCurve(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddCurve(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddCurve(System.Drawing.PointF[],System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddClosedCurve(System.Drawing.Point[],System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.get_PathPoints():System.Drawing.PointF[]")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddPolygon(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddCurve(System.Drawing.PointF[],System.Int32,System.Int32,System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath..ctor(System.Drawing.PointF[],System.Byte[],System.Drawing.Drawing2D.FillMode)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath._GetPathData():System.Drawing.Drawing2D.PathData")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddPolygon(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddClosedCurve(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath..ctor(System.Drawing.Point[],System.Byte[],System.Drawing.Drawing2D.FillMode)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.GraphicsPath.AddCurve(System.Drawing.Point[],System.Single):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix.TransformPoints(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix..ctor(System.Drawing.RectangleF,System.Drawing.PointF[])")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix.TransformVectors(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix.TransformPoints(System.Drawing.PointF[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix.TransformVectors(System.Drawing.Point[]):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix..ctor(System.Drawing.Rectangle,System.Drawing.Point[])")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="System.Drawing.Drawing2D.Matrix.get_Elements():System.Single[]")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="System.Drawing.SafeNativeMethods.IntCreateBitmap(System.Int32,System.Int32,System.Int32,System.Int32,System.IntPtr):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="System.Drawing.SafeNativeMethods.CreateBitmap(System.Int32,System.Int32,System.Int32,System.Int32,System.IntPtr):System.IntPtr")]

// For InProc SxS feature
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ActiveBorder()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ActiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ActiveCaptionText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_AppWorkspace()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ButtonFace()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ButtonHighlight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ButtonShadow()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_Control()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ControlDark()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ControlDarkDark()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ControlLight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ControlLightLight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ControlText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_Desktop()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_GradientActiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_GradientInactiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_GrayText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_Highlight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_HighlightText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_HotTrack()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_InactiveBorder()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_InactiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_InactiveCaptionText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_Info()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_InfoText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_Menu()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_MenuBar()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_MenuHighlight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_MenuText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_ScrollBar()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_Window()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_WindowFrame()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemBrushes.#get_WindowText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_CaptionFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_DefaultFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_DialogFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_IconTitleFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_MenuFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_MessageBoxFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_SmallCaptionFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemFonts.#get_StatusFont()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Application()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Asterisk()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Error()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Exclamation()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Hand()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Information()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Question()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Shield()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_Warning()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemIcons.#get_WinLogo()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ActiveBorder()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ActiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ActiveCaptionText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_AppWorkspace()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ButtonFace()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ButtonHighlight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ButtonShadow()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_Control()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ControlDark()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ControlDarkDark()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ControlLight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ControlLightLight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ControlText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_Desktop()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_GradientActiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_GradientInactiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_GrayText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_Highlight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_HighlightText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_HotTrack()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_InactiveBorder()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_InactiveCaption()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_InactiveCaptionText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_Info()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_InfoText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_Menu()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_MenuBar()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_MenuHighlight()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_MenuText()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_ScrollBar()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_Window()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_WindowFrame()")]
[module: SuppressMessage("Microsoft.SideBySide", "CA710:ExposedResourcesMustBeConsumed", Scope = "member", Target = "System.Drawing.SystemPens.#get_WindowText()")]

namespace System.Drawing 
{
}
