using System.Diagnostics.CodeAnalysis;

//***************************************************************************************************************************
// Warnings related to the No Primary Interop Assembly (NoPIA) are suppressed.  This is not relevant to WPF at the moment.
//***************************************************************************************************************************
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="_enumTypeConverterMap", Scope="member", Target="System.Windows.Baml2006.Baml2006Reader.#Process_PropertyWithConverter()")]
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="_masterTypeTable", Scope="member", Target="System.Windows.Baml2006.WpfSharedBamlSchemaContext.#GetKnownXamlType(System.Type)")]
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="_masterTypeTable", Scope="member", Target="System.Windows.Baml2006.WpfSharedBamlSchemaContext.#GetUnknownXamlType(System.Type)")]
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="_masterTypeTable", Scope="member", Target="System.Windows.Baml2006.WpfSharedXamlSchemaContext.#GetXamlType(System.Type)")]
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="initializedTypes", Scope="member", Target="System.Windows.Markup.RoutedEventValueSerializer.#ForceTypeConstructors(System.Type)")]
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="_allowedInternalTypes", Scope="member", Target="System.Windows.Markup.XamlTypeMapper+XamlTypeMapperSchemaContext.#GetInternalType(System.Type,System.Xaml.XamlType)")]
[module: SuppressMessage("Microsoft.Usage","CA2301:EmbeddableTypesInContainersRule", MessageId="_keyTypeMap", Scope="member", Target="System.Windows.Markup.Primitives.ElementPropertyBase.#GetDictionaryKeyType(System.Collections.IDictionary)")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="MS.Internal.Data.ValueConverterContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="MS.Internal.Documents.FixedDocumentPaginator")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="MS.Internal.Documents.FixedDocumentSequencePaginator")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="MS.Internal.Documents.FlowDocumentPaginator")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="MS.Internal.Documents.FlowDocumentView")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="MS.Internal.PtsHost.FlowDocumentPage")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.TemplateContent+ServiceProviderWrapper")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Baml2006.DeferredBinaryDeserializerExtension+DeferredBinaryDeserializerExtensionContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Baml2006.TypeConverterMarkupExtension+TypeConverterContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Controls.FlowDocumentScrollViewer")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Controls.TextBlock")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Controls.TextBoxView")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Controls.Primitives.DocumentPageView")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Controls.Primitives.DocumentViewerBase")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Documents.DPTypeDescriptorContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Documents.FixedDocument")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Documents.FixedDocumentPage")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Documents.FixedDocumentSequence")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Documents.FixedDocumentSequenceDocumentPage")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Documents.FlowDocument")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Interop.DocObjHost")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Markup.ProvideValueServiceProvider")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Markup.TypeConvertContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Markup.Primitives.ElementMarkupObject+ElementObjectContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Markup.Primitives.ElementPropertyBase+ElementPropertyContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Markup.Primitives.MarkupWriter+MarkupWriterContext")]
[module: SuppressMessage("Microsoft.Usage","CA2302:FlagServiceProviders", Scope="type", Target="System.Windows.Markup.Primitives.ValueSerializerContextWrapper")]
[module: SuppressMessage("Microsoft.Usage","CA2303:FlagTypeGetHashCode", Scope="member", Target="MS.Internal.Data.AccessorTable+AccessorTableKey.#GetHashCode()")]
[module: SuppressMessage("Microsoft.Usage","CA2303:FlagTypeGetHashCode", Scope="member", Target="MS.Internal.Data.DataBindEngine+ValueConverterTable+Key.#GetHashCode()")]
[module: SuppressMessage("Microsoft.Usage","CA2303:FlagTypeGetHashCode", Scope="member", Target="System.Windows.ComponentResourceKey.#GetHashCode()")]
[module: SuppressMessage("Microsoft.Usage","CA2303:FlagTypeGetHashCode", Scope="member", Target="System.Windows.Data.ValueConversionAttribute.#GetHashCode()")]
[module: SuppressMessage("Microsoft.Usage","CA2303:FlagTypeGetHashCode", Scope="member", Target="System.Windows.Markup.Primitives.ElementMarkupObject+ShouldSerializeKey.#GetHashCode()")]
